---
title: "Final Project Report"
author: "Damon Landis, Aaron Bowlin, Jackson Landsteiner"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Report

  Our project had the main goal of analyzing the differences between the two programs of R and Mathematica respectively. Aaron, Eli and myself were responsible for the R portion of the project and the data analysis to go along with that portion. Jackson, Josh and Dakota worked on the Mathematica portion of the project and gathered results so that we could compare and contrast the two programs. To begin our project, we first needed to obtain our data. Eli's capstone project was used as our data model. We first gathered that data and ran certain tests, like the T-test and ANOVA, in Excel so that it could be familiar to everyone in the project group. The R group, Aaron, Eli and Damon put together the R Markdown file. Damon ran and coded for the T-tests, Aaron ran and coded for the ANOVA test, and Eli made the R graph of our data. Jackson, Josh, and Dakota began their work in Mathematica after the R group finished. Their work included the same pieces of data as the R Markdown that was made first. Jackson ran the T-tests in Mathematica, Dakota ran the ANOVA, and Josh did the Mathematica graph. The tests ran by both programs gave similar results, except for the ANOVA test. Graphing the data in Mathematica proved to be much more difficult than R. We, as a group, concluded that R Markdown is the preferred data analysis tool due to its user friendliness along with the simplicity of putting together graphs and tables. This conclusion may be due to our familiarity with R versus Mathematica, but that does not mean that Mathematica is not a good choice for data analysis. 
Our project had the main goal of analyzing the differences between the two programs of R and Mathematica respectively. Aaron, Damon, and Eli all worked on the R portion of the project, while Josh, Dakota, and myself were resposible for the Mathematica portion of the project. We compiled the data from Eli's capstone project in order to compare and contrast the two programs. The data was gathered in an Excel file so it could be easily sent to the entire group. Each group was tasked with running two tests and a chart for the data. These two tests were the Paired T-tests and the ANOVA tests. I was tasked with making the T-Tests. Both programs were fairly easy to use for this function and the data came out similar. Overall, the result proved to be the same except for the ANOVA test on Mathematica did not seem to work as well. As a group we came to the conclusion that R Markdown was the preferred program due to its user friendliness. This conclusion could also be caused from some biased by some of the group members already having some expierenced with R Markdown
